mysql:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: demostoredb
    MYSQL_USER: demostore
    MYSQL_PASSWORD: hEMwqF6SMuz9m5gY
